# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
